
services:
  spark:
    image: apache/spark:3.5.6
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    environment:
      - SPARK_MASTER_HOST=0.0.0.0
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
    ports:
      - '8080:8080'
      - '7077:7077'
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"
      
  spark-worker:
    image: apache/spark:3.5.6
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark:7077  
    environment:
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=2g
    depends_on:
      - spark
    extra_hosts:
      - "host.docker.internal:${HOST_IP}"